import { Lead, Task, Service, EmailTemplate, Proposal, ContactHistory } from '@/types'

export const mockLeads: Lead[] = [
  {
    id: '1',
    first_name: 'Martina',
    last_name: 'Rodríguez',
    company: 'Consultora MR',
    email: 'martina@consultora.com',
    phone: '+54 11 5555-1234',
    instagram: '@martina.rodriguez',
    alpha_project: 'NahuelContent',
    service_interested: 'Dirección creativa',
    commercial_status: 'Propuesta enviada',
    temperature: 'Caliente',
    entry_channel: 'Instagram',
    first_contact_date: '2026-05-20',
    last_contact_date: '2026-06-05',
    next_step: 'Hacer seguimiento de la propuesta',
    follow_up_date: '2026-06-12',
    priority: 'Alta',
    estimated_value: 150000,
    currency: 'ARS',
    quick_notes: 'Muy interesada. Esperando respuesta del marido.',
    is_client: false,
    created_at: '2026-05-20T10:00:00Z',
    updated_at: '2026-06-05T14:00:00Z',
  },
  {
    id: '2',
    first_name: 'Tomás',
    last_name: 'García',
    company: 'Gym TG',
    email: 'tomas@gymtg.com',
    phone: '+54 11 5555-5678',
    instagram: '@tomasgarcia.fit',
    alpha_project: 'Alpha Studio',
    service_interested: 'Producción mensual',
    commercial_status: 'Reunión agendada',
    temperature: 'Caliente',
    entry_channel: 'Referido',
    first_contact_date: '2026-06-01',
    last_contact_date: '2026-06-10',
    next_step: 'Reunión el jueves a las 17hs',
    follow_up_date: '2026-06-13',
    priority: 'Alta',
    estimated_value: 200000,
    currency: 'ARS',
    quick_notes: 'Tiene presupuesto. Busca alguien confiable.',
    is_client: false,
    created_at: '2026-06-01T09:00:00Z',
    updated_at: '2026-06-10T11:00:00Z',
  },
  {
    id: '3',
    first_name: 'Lucía',
    last_name: 'Fernández',
    company: 'Tienda Lucía',
    email: 'lucia@tienda.com',
    alpha_project: 'Alpha Systems',
    service_interested: 'Implementación CRM',
    commercial_status: 'Necesita diagnóstico',
    temperature: 'Tibio',
    entry_channel: 'Web',
    first_contact_date: '2026-06-08',
    last_contact_date: '2026-06-08',
    next_step: 'Enviar formulario de diagnóstico',
    follow_up_date: '2026-06-14',
    priority: 'Media',
    estimated_value: 80000,
    currency: 'ARS',
    quick_notes: 'Tiene muchos leads pero los pierde todos.',
    is_client: false,
    created_at: '2026-06-08T16:00:00Z',
    updated_at: '2026-06-08T16:00:00Z',
  },
  {
    id: '4',
    first_name: 'Diego',
    last_name: 'Soria',
    company: '',
    instagram: '@diego_soria9',
    alpha_project: 'Alpha Athlete',
    service_interested: 'Highlights deportivos',
    commercial_status: 'Respondió',
    temperature: 'Tibio',
    entry_channel: 'Instagram',
    first_contact_date: '2026-06-05',
    last_contact_date: '2026-06-09',
    next_step: 'Pedir material de temporada',
    follow_up_date: '2026-06-15',
    priority: 'Media',
    estimated_value: 45000,
    currency: 'ARS',
    quick_notes: 'Jugador de fútbol semipro. Quiere enviar perfil a clubes.',
    is_client: false,
    created_at: '2026-06-05T12:00:00Z',
    updated_at: '2026-06-09T10:00:00Z',
  },
  {
    id: '5',
    first_name: 'Carolina',
    last_name: 'Méndez',
    company: 'CM Arquitectura',
    email: 'caro@cmarq.com',
    alpha_project: 'NahuelContent',
    service_interested: 'Dirección creativa',
    commercial_status: 'Cliente activo',
    temperature: 'Caliente',
    entry_channel: 'LinkedIn',
    first_contact_date: '2026-04-01',
    last_contact_date: '2026-06-01',
    next_step: 'Enviar resumen del mes',
    follow_up_date: '2026-06-20',
    priority: 'Alta',
    estimated_value: 150000,
    currency: 'ARS',
    quick_notes: 'Cliente activo. Mes 3. Muy conforme.',
    is_client: true,
    created_at: '2026-04-01T09:00:00Z',
    updated_at: '2026-06-01T14:00:00Z',
  },
  {
    id: '6',
    first_name: 'Ramón',
    last_name: 'Vega',
    company: 'Restaurante Vega',
    email: 'ramon@restaurantevega.com',
    alpha_project: 'Alpha Studio',
    service_interested: 'Producción mensual',
    commercial_status: 'Seguimiento pendiente',
    temperature: 'Tibio',
    entry_channel: 'WhatsApp',
    first_contact_date: '2026-05-15',
    last_contact_date: '2026-05-28',
    next_step: 'Recontactar con propuesta actualizada',
    follow_up_date: '2026-06-12',
    priority: 'Media',
    estimated_value: 120000,
    currency: 'ARS',
    quick_notes: 'Pidió pensar. Hace 2 semanas sin respuesta.',
    is_client: false,
    created_at: '2026-05-15T14:00:00Z',
    updated_at: '2026-05-28T16:00:00Z',
  },
  {
    id: '7',
    first_name: 'Valentina',
    last_name: 'Torres',
    company: 'VT Coaching',
    email: 'vale@vtcoaching.com',
    instagram: '@vale.torres.coach',
    alpha_project: 'NahuelContent',
    service_interested: 'Dirección creativa',
    commercial_status: 'Nuevo lead',
    temperature: 'Frío',
    entry_channel: 'Instagram',
    first_contact_date: '2026-06-11',
    last_contact_date: '2026-06-11',
    next_step: 'Responder con info inicial',
    follow_up_date: '2026-06-13',
    priority: 'Baja',
    quick_notes: 'Escribió por DM preguntando cómo trabajo.',
    is_client: false,
    created_at: '2026-06-11T20:00:00Z',
    updated_at: '2026-06-11T20:00:00Z',
  },
]

export const mockTasks: Task[] = [
  {
    id: '1',
    lead_id: '1',
    alpha_project: 'NahuelContent',
    title: 'Hacer seguimiento de propuesta',
    description: 'Martina lleva 7 días sin responder la propuesta. Contactar suavemente.',
    task_type: 'Seguimiento',
    status: 'Pendiente',
    priority: 'Alta',
    due_date: '2026-06-12',
    created_at: '2026-06-05T14:00:00Z',
    updated_at: '2026-06-05T14:00:00Z',
    lead: mockLeads[0],
  },
  {
    id: '2',
    lead_id: '2',
    alpha_project: 'Alpha Studio',
    title: 'Preparar agenda para reunión con Tomás',
    description: 'Definir qué mostrar en la reunión del jueves.',
    task_type: 'Reunión',
    status: 'Pendiente',
    priority: 'Alta',
    due_date: '2026-06-12',
    created_at: '2026-06-10T11:00:00Z',
    updated_at: '2026-06-10T11:00:00Z',
    lead: mockLeads[1],
  },
  {
    id: '3',
    lead_id: '6',
    alpha_project: 'Alpha Studio',
    title: 'Recontactar a Ramón Vega',
    description: 'Hace 2 semanas sin respuesta. Enviar seguimiento.',
    task_type: 'Seguimiento',
    status: 'Vencido',
    priority: 'Media',
    due_date: '2026-06-08',
    created_at: '2026-05-28T16:00:00Z',
    updated_at: '2026-05-28T16:00:00Z',
    lead: mockLeads[5],
  },
  {
    id: '4',
    lead_id: '5',
    alpha_project: 'NahuelContent',
    title: 'Enviar resumen del mes a Carolina',
    description: 'Resumen de resultados de mayo + plan de junio.',
    task_type: 'Entrega',
    status: 'Pendiente',
    priority: 'Alta',
    due_date: '2026-06-15',
    created_at: '2026-06-01T14:00:00Z',
    updated_at: '2026-06-01T14:00:00Z',
    lead: mockLeads[4],
  },
  {
    id: '5',
    lead_id: '3',
    alpha_project: 'Alpha Systems',
    title: 'Enviar formulario de diagnóstico a Lucía',
    task_type: 'Diagnóstico',
    status: 'En proceso',
    priority: 'Media',
    due_date: '2026-06-14',
    created_at: '2026-06-08T16:00:00Z',
    updated_at: '2026-06-08T16:00:00Z',
    lead: mockLeads[2],
  },
]

export const mockServices: Service[] = [
  {
    id: '1',
    alpha_project: 'NahuelContent',
    name: 'Dirección creativa',
    description: 'Servicio para ordenar el mensaje, definir cómo debe ser percibido el profesional y transformar su conocimiento en contenido estratégico.',
    ideal_client: 'Profesionales con experiencia que sienten que su contenido no los representa.',
    problem_solved: 'Falta de claridad, dirección y posicionamiento.',
    deliverables: 'Dirección mensual de contenido, revisión de piezas, estrategia editorial.',
    base_price: 150000,
    currency: 'ARS',
    duration: 'Mensual',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: '2',
    alpha_project: 'Alpha Studio',
    name: 'Producción mensual de contenido',
    description: 'Jornada mensual de producción + edición + piezas listas para publicar.',
    ideal_client: 'Marcas que necesitan contenido profesional constante.',
    problem_solved: 'Falta de contenido visual ordenado y profesional.',
    deliverables: 'Fotos, videos, reels, stories, piezas gráficas.',
    base_price: 200000,
    currency: 'ARS',
    duration: 'Mensual',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: '3',
    alpha_project: 'Alpha Systems',
    name: 'Implementación CRM',
    description: 'Sistema para ordenar leads, etapas, tareas, seguimiento y reportes.',
    ideal_client: 'Negocios que reciben consultas pero pierden oportunidades por falta de seguimiento.',
    problem_solved: 'Desorden comercial, leads sin seguimiento, oportunidades perdidas.',
    deliverables: 'CRM configurado, pipeline de ventas, flujos de seguimiento.',
    base_price: 80000,
    currency: 'ARS',
    duration: 'Proyecto único',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: '4',
    alpha_project: 'Alpha Athlete',
    name: 'Highlights deportivos',
    description: 'Edición de highlights, presentación deportiva y perfil visual.',
    ideal_client: 'Deportistas que necesitan mostrarse profesionalmente.',
    problem_solved: 'Falta de material deportivo claro, atractivo y profesional.',
    deliverables: 'Video de highlights, perfil deportivo, contenido para redes.',
    base_price: 45000,
    currency: 'ARS',
    duration: 'Por proyecto',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
]

export const mockEmailTemplates: EmailTemplate[] = [
  {
    id: '1',
    title: 'NahuelContent — Respuesta cuando pide más info',
    alpha_project: 'NahuelContent',
    service_id: '1',
    commercial_stage: 'Respuesta cuando pide más información',
    recommended_temperature: 'Tibio',
    subject: 'Sobre cómo trabajo la dirección creativa',
    body: `Hola [Nombre], ¿cómo estás?

Te cuento brevemente cómo trabajo.

Mi enfoque no es simplemente ayudarte a publicar más contenido, sino ordenar qué querés comunicar, cómo querés ser percibido/a y cómo transformar tu experiencia en contenido que realmente te posicione.

Normalmente empezamos con un diagnóstico de tu perfil, tu mensaje actual y el tipo de cliente o audiencia que querés atraer. A partir de eso, armamos una dirección clara para que cada contenido tenga intención y no sea solamente una publicación más.

La idea es que tu contenido empiece a representar mejor lo que sabés, lo que hacés y el nivel profesional que querés transmitir.

Si te parece, puedo pasarte cómo sería la modalidad de trabajo y qué incluiría.`,
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: '2',
    title: 'Alpha Studio — Respuesta cuando pide más info',
    alpha_project: 'Alpha Studio',
    service_id: '2',
    commercial_stage: 'Respuesta cuando pide más información',
    recommended_temperature: 'Tibio',
    subject: 'Sobre cómo podríamos trabajar tu contenido',
    body: `Hola [Nombre], ¿cómo estás?

Te cuento brevemente cómo trabajamos desde Alpha Studio.

La idea es ayudarte a resolver la producción de contenido de una forma más ordenada y profesional, para que tu marca tenga material visual claro, consistente y listo para publicar.

Normalmente trabajamos con una planificación previa, una jornada de producción y luego la edición de las piezas necesarias para el mes.

No se trata solo de grabar o sacar fotos, sino de que el contenido tenga una intención clara y represente bien lo que la marca quiere comunicar.

Si querés, puedo pasarte una modalidad posible según lo que necesite [Marca].`,
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: '3',
    title: 'Alpha Systems — Respuesta cuando pide más info',
    alpha_project: 'Alpha Systems',
    service_id: '3',
    commercial_stage: 'Respuesta cuando pide más información',
    recommended_temperature: 'Tibio',
    subject: 'Sobre cómo podríamos ordenar tu sistema comercial',
    body: `Hola [Nombre], ¿cómo estás?

Te cuento un poco cómo trabajamos desde Alpha Systems.

La idea no es sumar una herramienta más porque sí, sino ordenar todo el proceso comercial: desde que entra una consulta hasta que se hace seguimiento, se agenda, se vende o se reactiva más adelante.

Muchas veces el problema no es la falta de leads, sino que no hay un sistema claro para saber en qué estado está cada persona, qué se le respondió, qué falta hacer y cuándo volver a contactarla.

Lo que hacemos es armar un sistema simple para que puedas ver tus oportunidades, ordenar tus contactos, seguir cada caso y no perder ventas por desorganización.

Si querés, puedo hacerte unas preguntas rápidas para entender cómo están manejando hoy las consultas y decirte qué sistema tendría más sentido.`,
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: '4',
    title: 'Alpha Athlete — Respuesta cuando pide más info',
    alpha_project: 'Alpha Athlete',
    service_id: '4',
    commercial_stage: 'Respuesta cuando pide más información',
    recommended_temperature: 'Tibio',
    subject: 'Sobre cómo podemos armar tu material deportivo',
    body: `Hola [Nombre], ¿cómo estás?

Te cuento brevemente cómo trabajamos desde Alpha Athlete.

La idea es ayudarte a mostrarte de una forma más profesional como deportista, ordenando tu material y transformándolo en piezas claras, atractivas y fáciles de compartir.

Podemos trabajar highlights, videos para enviar a clubes, perfil deportivo y contenido para que tu Instagram comunique mejor tu nivel.

No se trata solo de editar jugadas lindas, sino de mostrar tu rendimiento con criterio y dirección.

Si querés, puedo pasarte qué necesitaríamos para empezar y qué opciones tendría más sentido según tu caso.`,
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: '5',
    title: 'NahuelContent — Seguimiento suave después de propuesta',
    alpha_project: 'NahuelContent',
    service_id: '1',
    commercial_stage: 'Seguimiento suave',
    recommended_temperature: 'Caliente',
    subject: 'Sobre la propuesta que te envié',
    body: `Hola [Nombre], ¿cómo vas?

Te escribo para ver si tuviste oportunidad de revisar lo que te envié.

Quedo disponible si tenés alguna pregunta o si querés que ajustemos algo antes de arrancar.`,
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
]

export const mockProposals: Proposal[] = [
  {
    id: '1',
    lead_id: '1',
    service_id: '1',
    title: 'Propuesta dirección creativa — Martina Rodríguez',
    amount: 150000,
    currency: 'ARS',
    sent_date: '2026-06-05',
    status: 'Enviada',
    notes: 'Incluye 1 mes de dirección + revisión de 8 piezas.',
    created_at: '2026-06-05T14:00:00Z',
    updated_at: '2026-06-05T14:00:00Z',
    lead: mockLeads[0],
  },
  {
    id: '2',
    lead_id: '2',
    service_id: '2',
    title: 'Propuesta producción mensual — Gym TG',
    amount: 200000,
    currency: 'ARS',
    sent_date: '2026-06-10',
    status: 'Vista',
    notes: 'Jornada mensual + 20 piezas editadas.',
    created_at: '2026-06-10T11:00:00Z',
    updated_at: '2026-06-10T11:00:00Z',
    lead: mockLeads[1],
  },
]

export const mockHistory: ContactHistory[] = [
  {
    id: '1',
    lead_id: '1',
    date: '2026-05-20',
    interaction_type: 'Primer contacto',
    channel: 'Instagram',
    summary: 'Martina escribió por DM preguntando sobre servicios de contenido.',
    result: 'Respondí con info general y pregunté sobre su situación.',
    next_action: 'Enviar propuesta si hay interés.',
    created_at: '2026-05-20T10:00:00Z',
  },
  {
    id: '2',
    lead_id: '1',
    date: '2026-06-05',
    interaction_type: 'Propuesta enviada',
    channel: 'Email',
    summary: 'Envié propuesta formal de dirección creativa.',
    result: 'Propuesta enviada. Esperando respuesta.',
    next_action: 'Seguimiento el 12/06.',
    created_at: '2026-06-05T14:00:00Z',
  },
]
